name: LegendCore
version: ${project.version}
main: com.legendsmp.legendcore.LegendCore
api-version: 1.16
authors: [ NateKrauss ]
description: This is the core plugin for Legendary SMP
commands:
  suicide:
      description: Die fool.
      aliases: [kms, die]
  heal:
      description: Get some health!
  feed:
      description: Lunch time!
      aliases: [food, hunger]
  weather:
      description: Gain the powers of Zeus!
  flight:
      description: Red bull gives you wings!
      aliases: [fly, flying]
  nick:
      description: Plastic surgery for words?
      aliases: [nickname]