name: LegendCore
version: ${project.version}
main: com.legendsmp.legendcore.LegendCore
api-version: 1.16
authors: [ NateKrauss ]
description: This is the core plugin for Legendary SMP
commands:
  suicide:
      description: Die fool.

  heal:
      description: Get some health!
  feed:
      description: Lunch time!
